name: Download new assets

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

concurrency:
  group: ${{ github.ref }}

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'master'
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          dotnet: false
          large-packages: false
      - name: Remove all .NET versions
        run: |
          sudo apt-get remove --purge -y dotnet* || true
          sudo apt-get autoremove -y
          sudo rm -rf /usr/share/dotnet /etc/dotnet
      - name: Install .NET 6.0
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 6.0.x
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Set env
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config http.postBuffer 2147483648
            if [[ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]]; then echo "FORCE=--force" >> $GITHUB_ENV; fi
      - name: Update files
        run: |
          python -m pip install -U requests
          python script.py ${{ env.FORCE }}
